[package]
name = "repos-list-check"
version = "0.1.0"
edition = "2018"

[dependencies]
comrak = "0.4.1"
futures = "0.1.25"
hubcaps = { version = "0.5.0", features = ["tls", "httpcache"] }
hyper = "0.12.23"
hyper-tls = "0.3.1"
regex = "1.1.0"
tokio = "0.1.15"
